FROM docker.io/library/node:22-bookworm-slim

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install --save @types/plotly.js-basic-dist

COPY . .

RUN npm install

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
