services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "5173:5173"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
