# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: AcidWatch Documentation
repo_url: https://github.com/equinor/acidwatch
repo_name: equinor/acidwatch

theme:
  name: material
  favicon: assets/images/icon.svg
  logo: assets/images/icon.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs

nav:
- Home: index.md
- Client & CLI:
  - client/getting_started.md
  - API Reference:
    - Client: client/reference/client.md
- Server & Adapters:
  - server/getting_started.md
  - API Reference:
    - BaseAdapter: server/reference/base_adapter.md

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_typingdoc
          show_source: false
          show_root_heading: true
          show_if_no_docstring: true
          preload_modules:
          - pydantic
          inherited_members: true
          members_order: source
          separate_signature: false
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_attribute_values: false
          show_signature_annotations: true
          show_signature_type_parameters: true
