[project]
name = "acidwatch-docs"
version = "0.1.0"
description = "Metapackage for AcidWatch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "griffe-typingdoc>=0.3.1",
    "mkdocstrings[python]>=1.0.4",
    "zensical>=0.0.46",
    "acidwatch-api",
    "acidwatch",
]

[tool.uv.workspace]
members = ["backend", "backend/packages/*", "workers/*"]

[tool.uv.sources]
acidwatch = { workspace = true }
acidwatch-api = { workspace = true }
acidwatch-messaging = { workspace = true }
acidwatch-models = { workspace = true }
acidwatch-worker-runtime = { workspace = true }
acidwatch-worker-arcs = { workspace = true }
acidwatch-worker-arcs-exp = { workspace = true }
acidwatch-worker-gibbs-minimization = { workspace = true }
acidwatch-worker-phpitz-reactive = { workspace = true }
acidwatch-worker-phpitz-solubility = { workspace = true }
acidwatch-worker-srk-vanlaar = { workspace = true }
acidwatch-worker-tocomo = { workspace = true }
