# yaml-language-server: $schema=https://raw.githubusercontent.com/equinor/radix-operator/release/json-schema/radixapplication.json
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: aw-wip-messagebroker
spec:
    environments:
        - name: wip-msgbr
          build:
              from: wip-messagebroker
    components:
        - name: frontend
          variables:
              TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    CLIENT_ID: bb73aaf4-9ddb-4229-a3a1-008faebe30b7
                    API_URL: https://backend-aw-wip-messagebroker-wip-msgbr.playground.radix.equinor.com
          ports:
              - name: http
                port: 5200
          publicPort: http
          src: frontend
        - name: backend
          variables:
              TRANSPORT_BACKEND: servicebus
          secrets:
              - BROKER_URL
          network:
              ingress:
                  public:
                      proxyReadTimeout: 300
                      proxySendTimeout: 300
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    ACIDWATCH_ENV: production
                    FRONTEND_URI: https://frontend-aw-wip-messagebroker-wip-msgbr.playground.radix.equinor.com
                    FRONTEND_CLIENT_ID: 49385006-e775-4109-9635-2f1a2bdc8ea8
                    BACKEND_CLIENT_ID: 456cc109-08d7-4c11-bf2e-a7b26660f99e
                    BACKEND_API_SCOPE: api://456cc109-08d7-4c11-bf2e-a7b26660f99e/AcidWatch.User
                    PHPITZ_API_BASE_URI: https://backend-phpitz-dev.radix.equinor.com
                    APPLICATIONINSIGHTS_CONNECTION_STRING: ""
                    OASIS_URI: https://api-oasis-test.radix.equinor.com
          publicPort: http
          ports:
              - name: http
                port: 8000
          dockerfileName: backend/Dockerfile
          resources:
              requests:
                  memory: "800M"
                  cpu: "4000m"
              limits:
                  memory: "800M"
                  cpu: "4000m"
        - name: worker-tocomo
          dockerfileName: workers/tocomo/Dockerfile
          variables:
              TRANSPORT_BACKEND: servicebus
          secrets:
              - BROKER_URL
          horizontalScaling:
              minReplicas: 0
              maxReplicas: 5
              cooldownPeriod: 600
              triggers:
                  - name: jobs
                    azureServiceBus:
                        namespace: aw-wip-messagebroker
                        queueName: acidwatch.tocomo
                        messageCount: 1
                        connectionFromEnv: BROKER_URL
        - name: worker-arcs-exp
          dockerfileName: workers/arcs-exp/Dockerfile
          variables:
              TRANSPORT_BACKEND: servicebus
          secrets:
              - BROKER_URL
          horizontalScaling:
              minReplicas: 0
              maxReplicas: 5
              cooldownPeriod: 600
              triggers:
                  - name: jobs
                    azureServiceBus:
                        namespace: aw-wip-messagebroker
                        queueName: acidwatch.arcs_exp
                        messageCount: 1
                        connectionFromEnv: BROKER_URL
        - name: worker-solubilityccs
          dockerfileName: workers/solubilityccs/Dockerfile
          variables:
              TRANSPORT_BACKEND: servicebus
          secrets:
              - BROKER_URL
          horizontalScaling:
              minReplicas: 0
              maxReplicas: 5
              cooldownPeriod: 600
              triggers:
                  - name: jobs
                    azureServiceBus:
                        namespace: aw-wip-messagebroker
                        queueName: acidwatch.solubilityccs
                        messageCount: 1
                        connectionFromEnv: BROKER_URL
        - name: worker-gibbs
          dockerfileName: workers/gibbs-minimization/Dockerfile
          variables:
              TRANSPORT_BACKEND: servicebus
          secrets:
              - BROKER_URL
          horizontalScaling:
              minReplicas: 0
              maxReplicas: 5
              cooldownPeriod: 600
              triggers:
                  - name: jobs
                    azureServiceBus:
                        namespace: aw-wip-messagebroker
                        queueName: acidwatch.gibbs_minimization
                        messageCount: 1
                        connectionFromEnv: BROKER_URL
        - name: worker-phpitz-reactive
          dockerfileName: workers/phpitz-reactive/Dockerfile
          variables:
              TRANSPORT_BACKEND: servicebus
          secrets:
              - BROKER_URL
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    PHPITZ_API_BASE_URI: https://backend-phpitz-dev.radix.equinor.com
          horizontalScaling:
              minReplicas: 0
              maxReplicas: 5
              cooldownPeriod: 600
              triggers:
                  - name: jobs
                    azureServiceBus:
                        namespace: aw-wip-messagebroker
                        queueName: acidwatch.phpitz_reactive
                        messageCount: 1
                        connectionFromEnv: BROKER_URL
        - name: worker-phpitz-solubility
          dockerfileName: workers/phpitz-solubility/Dockerfile
          variables:
              TRANSPORT_BACKEND: servicebus
          secrets:
              - BROKER_URL
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    PHPITZ_API_BASE_URI: https://backend-phpitz-dev.radix.equinor.com
          horizontalScaling:
              minReplicas: 0
              maxReplicas: 5
              cooldownPeriod: 600
              triggers:
                  - name: jobs
                    azureServiceBus:
                        namespace: aw-wip-messagebroker
                        queueName: acidwatch.phpitz_solubility
                        messageCount: 1
                        connectionFromEnv: BROKER_URL
