apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: acidwatch
spec:
    environments:
        - name: dev
          build:
              from: main
        - name: test
          build:
              from: main
        - name: prod
    dnsAlias:
        - alias: acidwatch
          component: frontend
          environment: prod
    components:
        - name: frontend
          variables:
              TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          environmentConfig:
              - environment: dev
                variables:
                    CLIENT_ID: 49385006-e775-4109-9635-2f1a2bdc8ea8
                    API_URL: https://backend-acidwatch-dev.radix.equinor.com
                    API_SCOPE: api://456cc109-08d7-4c11-bf2e-a7b26660f99e/AcidWatch.User
                    APPINSIGHTS_CONNECTIONSTRING:
                    OASIS_URL: https://api-oasis-test.radix.equinor.com
                    OASIS_HOST: api-oasis-test.radix.equinor.com
                    OASIS_SCOPE: d2e2c318-b49a-4174-b4b4-256751558dc5/user_impersonation
              - environment: test
                variables:
                    CLIENT_ID: 49385006-e775-4109-9635-2f1a2bdc8ea8
                    API_URL: https://backend-acidwatch-dev.radix.equinor.com
                    API_SCOPE: api://456cc109-08d7-4c11-bf2e-a7b26660f99e/AcidWatch.User
                    APPINSIGHTS_CONNECTIONSTRING:
                    OASIS_URL: https://api-oasis-test.radix.equinor.com
                    OASIS_HOST: api-oasis-test.radix.equinor.com
                    OASIS_SCOPE: d2e2c318-b49a-4174-b4b4-256751558dc5/user_impersonation
              - environment: prod
                variables:
                    CLIENT_ID: bb73aaf4-9ddb-4229-a3a1-008faebe30b7
                    API_URL: https://backend-acidwatch-prod.radix.equinor.com
                    API_SCOPE:
                    APPINSIGHTS_CONNECTIONSTRING:
                    OASIS_URL: https://api-oasis-prod.radix.equinor.com
                    OASIS_HOST: api-oasis-prod.radix.equinor.com
                    OASIS_SCOPE: c4443782-66d0-4426-8a13-ef29109cd8ce/user_impersonation
          ports:
              - name: http
                port: 5200
          publicPort: http
          src: frontend
        - name: backend
          network:
              ingress:
                  public:
                      proxyReadTimeout: 300
                      proxySendTimeout: 300
          secrets:
              - BACKEND_CLIENT_SECRET
              - CONNECTION_STRING
          environmentConfig:
              - environment: dev
                variables:
                    FRONTEND_CLIENT_ID: 49385006-e775-4109-9635-2f1a2bdc8ea8
                    BACKEND_CLIENT_ID: 456cc109-08d7-4c11-bf2e-a7b26660f99e
                    BACKEND_API_SCOPE: api://456cc109-08d7-4c11-bf2e-a7b26660f99e/AcidWatch.User
                    CO2SPEC_API_SCOPE: api://a4f4519a-fafb-48c2-9a5c-3ba38309a824/co2specdemo.user
                    CO2SPEC_API_BASE_URI: https://backend-co2specdemo-dev.radix.equinor.com
                    ARCS_API_BASE_URI: https://api-arcs-dev.radix.equinor.com
                    APP_INSIGHTS_CONNECTION_STRING:
              - environment: prod
                variables:
                    FRONTEND_CLIENT_ID: bb73aaf4-9ddb-4229-a3a1-008faebe30b7
                    BACKEND_CLIENT_ID: 873cbfab-30ca-4323-b5d5-e7955cc89ad9
                    BACKEND_API_SCOPE: api://873cbfab-30ca-4323-b5d5-e7955cc89ad9/AcidWatch.User
                    CO2SPEC_API_SCOPE: api://a4f4519a-fafb-48c2-9a5c-3ba38309a824/co2specdemo.user
                    CO2SPEC_API_BASE_URI: https://backend-co2specdemo-prod.radix.equinor.com
                    ARCS_API_BASE_URI: https://api-arcs-prod.radix.equinor.com
                    APP_INSIGHTS_CONNECTION_STRING:
          publicPort: http
          ports:
              - name: http
                port: 8000
          src: backend
