apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
    name: aw-wip-messagebroker
spec:
    environments:
        - name: wip-msgbr
          build:
              from: wip-messagebroker
    dnsAlias:
        - alias: acidwatch
          component: frontend
          environment: prod
    components:
        - name: frontend
          variables:
              TENANT_ID: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    CLIENT_ID: bb73aaf4-9ddb-4229-a3a1-008faebe30b7
                    API_URL: https://backend-acidwatch-wip-msgbr.playground.radix.equinor.com
          ports:
              - name: http
                port: 5200
          publicPort: http
          src: frontend
        - name: backend
          variables:
              BROKER_URL: amqp://guest:guest@rabbitmq:5672/
              TRANSPORT_BACKEND: rabbitmq
          network:
              ingress:
                  public:
                      proxyReadTimeout: 300
                      proxySendTimeout: 300
          secrets:
              - BACKEND_CLIENT_SECRET
              - CONNECTION_STRING
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    ACIDWATCH_ENV: production
                    FRONTEND_URI: https://frontend-acidwatch-wip-msgbr.playground.radix.equinor.com
                    FRONTEND_CLIENT_ID: 49385006-e775-4109-9635-2f1a2bdc8ea8
                    BACKEND_CLIENT_ID: 456cc109-08d7-4c11-bf2e-a7b26660f99e
                    BACKEND_API_SCOPE: api://456cc109-08d7-4c11-bf2e-a7b26660f99e/AcidWatch.User
                    TOCOMO_API_BASE_URI: https://backend-tocomo-dev.radix.equinor.com
                    ARCS_API_BASE_URI: https://api-arcs-eq-fork.radix.equinor.com
                    ARCS_EXP_API_BASE_URI: https://api-arcs-dev.radix.equinor.com
                    PHPITZ_API_BASE_URI: https://backend-phpitz-dev.radix.equinor.com
                    APPLICATIONINSIGHTS_CONNECTION_STRING:
                    OASIS_URI: https://api-oasis-test.radix.equinor.com
          publicPort: http
          ports:
              - name: http
                port: 8000
          dockerfileName: backend/Dockerfile
          resources:
              requests:
                  memory: "800M"
                  cpu: "4000m"
              limits:
                  memory: "800M"
                  cpu: "4000m"
        - name: rabbitmq
          image: rabbitmq:4-alpine
          ports:
              - name: amqp
                port: 5672
        - name: worker-tocomo
          dockerfileName: workers/tocomo/Dockerfile
          variables:
              BROKER_URL: amqp://guest:guest@rabbitmq:5672/
              TRANSPORT_BACKEND: rabbitmq
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    TOCOMO_API_BASE_URI: https://backend-tocomo-dev.radix.equinor.com
        - name: worker-arcs
          dockerfileName: workers/arcs/Dockerfile
          variables:
              BROKER_URL: amqp://guest:guest@rabbitmq:5672/
              TRANSPORT_BACKEND: rabbitmq
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    ARCS_API_BASE_URI: https://api-arcs-eq-fork.radix.equinor.com
        - name: worker-arcs-exp
          dockerfileName: workers/arcs-exp/Dockerfile
          variables:
              BROKER_URL: amqp://guest:guest@rabbitmq:5672/
              TRANSPORT_BACKEND: rabbitmq
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    ARCS_EXP_API_BASE_URI: https://api-arcs-dev.radix.equinor.com
        - name: worker-solubilityccs
          dockerfileName: workers/solubilityccs/Dockerfile
          variables:
              BROKER_URL: amqp://guest:guest@rabbitmq:5672/
              TRANSPORT_BACKEND: rabbitmq
        - name: worker-gibbs
          dockerfileName: workers/gibbs-minimization/Dockerfile
          variables:
              BROKER_URL: amqp://guest:guest@rabbitmq:5672/
              TRANSPORT_BACKEND: rabbitmq
        - name: worker-phpitz-reactive
          dockerfileName: workers/phpitz-reactive/Dockerfile
          variables:
              BROKER_URL: amqp://guest:guest@rabbitmq:5672/
              TRANSPORT_BACKEND: rabbitmq
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    PHPITZ_API_BASE_URI: https://backend-phpitz-dev.radix.equinor.com
        - name: worker-phpitz-solubility
          dockerfileName: workers/phpitz-solubility/Dockerfile
          variables:
              BROKER_URL: amqp://guest:guest@rabbitmq:5672/
              TRANSPORT_BACKEND: rabbitmq
          environmentConfig:
              - environment: wip-msgbr
                variables:
                    PHPITZ_API_BASE_URI: https://backend-phpitz-dev.radix.equinor.com
