import { ExperimentResult } from "../dto/ExperimentResult";

export const openKDCResults: ExperimentResult[] = [
    {
        final_concentrations: {
            H2O: 90,
            H2S: NaN,
            NO: 30.0,
            NO2: 10.0,
            O2: NaN,
            SO2: 30.0,
        },
        initial_concentrations: {
            H2O: 160,
            H2S: 0,
            NO2: 100,
            O2: 0,
            SO2: 80,
        },
        name: "WP2-6",
        pressure: 100,
        temperature: 25,
        time: 0,
    },
    {
        final_concentrations: {
            H2O: 400,
            H2S: 48.0,
            NO: 120.0,
            NO2: 0.0,
            O2: NaN,
            SO2: 55.0,
        },
        initial_concentrations: {
            H2O: 300,
            H2S: 100,
            NO2: 100,
            O2: 0,
            SO2: 0,
        },
        name: "WP2-7",
        pressure: 100,
        temperature: 25,
        time: 0,
    },
    {
        final_concentrations: {
            H2O: 40,
            H2S: NaN,
            NO: 60.0,
            NO2: 3.0,
            O2: NaN,
            SO2: NaN,
        },
        initial_concentrations: {
            H2O: 122,
            H2S: 0,
            NO2: 48,
            O2: 0,
            SO2: 35,
        },
        name: "WP3-2",
        pressure: 100,
        temperature: 25,
        time: 0,
    },
    {
        final_concentrations: {
            H2O: 35,
            H2S: NaN,
            NO: NaN,
            NO2: NaN,
            O2: NaN,
            SO2: NaN,
        },
        initial_concentrations: {
            H2O: 123,
            H2S: 0,
            NO2: 48,
            O2: 140,
            SO2: 35,
        },
        name: "WP3-2",
        pressure: 100,
        temperature: 25,
        time: 0,
    },
    {
        final_concentrations: {
            H2O: 20,
            H2S: 10.0,
            NO: 0.0,
            NO2: 0.0,
            O2: NaN,
            SO2: 23.0,
        },
        initial_concentrations: {
            H2O: 10,
            H2S: 65,
            NO2: 48,
            O2: 140,
            SO2: 35,
        },
        name: "WP5-1",
        pressure: 100,
        temperature: 25,
        time: 0,
    },
    {
        final_concentrations: {
            H2O: 470,
            H2S: 35.0,
            NO: 160.0,
            NO2: 0.0,
            O2: NaN,
            SO2: 205.0,
        },
        initial_concentrations: {
            H2O: 300,
            H2S: 100,
            NO2: 100,
            O2: 0,
            SO2: 100,
        },
        name: "WP5-2",
        pressure: 100,
        temperature: 25,
        time: 0,
    },
    {
        final_concentrations: {
            H2O: 840,
            H2S: 20.0,
            NO: 140.0,
            NO2: 0.0,
            O2: NaN,
            SO2: 260.0,
        },
        initial_concentrations: {
            H2O: 300,
            H2S: 100,
            NO2: 100,
            O2: 0,
            SO2: 100,
        },
        name: "WP5-5",
        pressure: 100,
        temperature: 25,
        time: 0,
    },
    {
        final_concentrations: {
            H2O: 60,
            H2S: 0.0,
            NO: NaN,
            NO2: NaN,
            O2: NaN,
            SO2: NaN,
        },
        initial_concentrations: {
            H2O: 300,
            H2S: 100,
            NO2: 140,
            O2: 350,
            SO2: 100,
        },
        name: "WP5-3",
        pressure: 100,
        temperature: 25,
        time: 0,
    },
    {
        final_concentrations: {
            H2O: 90,
            H2S: 0.0,
            NO: NaN,
            NO2: 63.0,
            O2: NaN,
            SO2: NaN,
        },
        initial_concentrations: {
            H2O: 300,
            H2S: 100,
            NO2: 140,
            O2: 350,
            SO2: 100,
        },
        name: "WP5-4",
        pressure: 100,
        temperature: 45,
        time: 0,
    },
];
