// Laboratory results from
//
// @article{morland2019acid,
//   title={Acid reactions in hub systems consisting of separate non-reactive CO2 transport lines},
//   author={Morland, Bj{\o}rn H and Tjelta, Morten and Norby, Truls and Svenningsen, Gaute},
//   journal={International Journal of Greenhouse Gas Control},
//   volume={87},
//   pages={246--255},
//   year={2019},
//   publisher={Elsevier}
// }
// @inproceedings{svenningsen2024impurity,
//   title={Impurity reactions in subsea CO2 pipelines},
//   author={Svenningsen, Gaute and Morland, Bj{\o}rn H and Solberg, Klas},
//   booktitle={Proceedings of the 17th Greenhouse Gas Control Technologies Conference (GHGT-17)},
//   pages={20--24},
//   year={2024}
// }
// @inproceedings{svenningsen2024experimental,
//   title={Experimental Testing of CO2 Specifications Under Simulated Ship Transport Conditions},
//   author={Svenningsen, Gaute and Morland, Bj{\o}rn H},
//   booktitle={Proceedings of the 17th Greenhouse Gas Control Technologies Conference (GHGT-17)},
//   pages={20--24},
//   year={2024}
// }

import { ExperimentResult } from "@/dto/ExperimentResult";

export const paperResults: ExperimentResult[] = [
    {
        finalConcentrations: {
            H2O: 450,
            H2S: 0,
            SO2: 8.5,
            NO2: 0.2,
            O2: 4,
            NO: 1,
        },
        initialConcentrations: {
            H2O: 100,
            H2S: 5.5,
            SO2: 5,
            NO2: 5,
            O2: 12,
        },
        name: "Hub01_1 [morland2019acid]",
        pressure: 100,
        temperature: 25,
        time: 26,
    },
    {
        finalConcentrations: {
            H2O: 550,
            H2S: 0,
            SO2: 12,
            NO2: 0,
            O2: 0.5,
            NO: 4,
        },
        initialConcentrations: {
            H2O: 100,
            H2S: 5.5,
            SO2: 5,
            NO2: 5,
            O2: 12,
        },
        name: "Hub01_2 [morland2019acid]",
        pressure: 100,
        temperature: 25,
        time: 163,
    },
    {
        finalConcentrations: {
            H2O: 75,
            H2S: 0,
            SO2: 21,
            NO2: 8,
            O2: 9,
            NO: 1.5,
        },
        initialConcentrations: {
            H2O: 35,
            H2S: 10,
            SO2: 12,
            NO2: 10,
            O2: 31,
        },
        name: "Hub02 [morland2019acid]",
        pressure: 100,
        temperature: 25,
        time: 84,
    },
    {
        finalConcentrations: {
            H2O: 96,
            H2S: 0,
            SO2: 32,
            NO2: 4,
            O2: 0,
            NO: 5,
        },
        initialConcentrations: {
            H2O: 120,
            H2S: 41,
            SO2: 38,
            NO2: 26,
            O2: 95,
        },
        name: "Hub03 [morland2019acid]",
        pressure: 100,
        temperature: 25,
        time: 84,
    },
    {
        finalConcentrations: {
            H2O: 35,
            H2S: 0,
            SO2: 12,
            NO2: 0,
            O2: 4,
            NO: 0,
        },
        initialConcentrations: {
            H2O: 32,
            H2S: 8,
            SO2: 9,
            NO2: 5,
            O2: 10,
        },
        name: "Exp1_B [svenningsen2024impurity]",
        pressure: 99,
        temperature: 4,
        time: 26,
    },
    {
        finalConcentrations: {
            H2O: 35,
            H2S: 0,
            SO2: 15,
            NO2: 0,
            O2: 0,
            NO: 4,
        },
        initialConcentrations: {
            H2O: 32,
            H2S: 8,
            SO2: 9,
            NO2: 10,
            O2: 10,
        },
        name: "Exp1_E [svenningsen2024impurity]",
        pressure: 99,
        temperature: 4,
        time: 507,
    },
    {
        finalConcentrations: {
            H2O: 48,
            H2S: 48,
            SO2: 18,
            NO2: 0,
            O2: 0,
            NO: 5,
        },
        initialConcentrations: {
            H2O: 35,
            H2S: 60,
            SO2: 10,
            NO2: 10,
            O2: 10,
        },
        name: "Exp2_C [svenningsen2024impurity]",
        pressure: 97,
        temperature: 4,
        time: 26,
    },
    {
        finalConcentrations: {
            H2O: 9,
            H2S: 0,
            SO2: 16,
            NO2: 0,
            O2: 0,
            NO: 7,
        },
        initialConcentrations: {
            H2O: 13,
            H2S: 10,
            SO2: 10,
            NO2: 10,
            O2: 11,
        },
        name: "Exp1_D [svenningsen2024experimental]",
        pressure: 20,
        temperature: -24,
        time: 144,
    },
    {
        finalConcentrations: {
            H2O: 9,
            H2S: 0,
            SO2: 20,
            NO2: 0,
            O2: 0,
            NO: 7,
        },
        initialConcentrations: {
            H2O: 57,
            H2S: 0,
            SO2: 10,
            NO2: 13,
            O2: 15,
            CO: 96,
            CH3CHO: 200, // Acetaldehyde
        },
        name: "Exp2_C [svenningsen2024experimental]",
        pressure: 20,
        temperature: -26,
        time: 167,
    },
];
