import { ExperimentResult } from "@/dto/ExperimentResult";

export const experiments: ExperimentResult[] = [
    {
        finalConcentrations: {
            H2O: 52,
            H2S: 0,
            SO2: 0,
            NO2: 5.5,
            O2: 30,
            NO: 0.3,
            N2O: 0.3,
            HNO3: 0.5,
        },
        initialConcentrations: {
            H2O: 52,
            H2S: 0,
            SO2: 0,
            NO2: 9,
            O2: 30,
            NO: 0,
        },
        name: "Exp1_A",
        pressure: 100,
        temperature: 2,
        time: 61,
    },
    {
        finalConcentrations: {
            H2O: 50,
            H2S: 0,
            SO2: 1,
            NO2: 5.2,
            O2: 30,
            NO: 0.3,
            N2O: 0.3,
            HNO3: 0.5,
        },
        initialConcentrations: {
            H2O: 52,
            H2S: 0,
            SO2: 1,
            NO2: 9,
            O2: 30,
            NO: 0,
        },
        name: "Exp1_B",
        pressure: 100,
        temperature: 2,
        time: 77,
    },
    {
        finalConcentrations: {
            H2O: 46,
            H2S: 0,
            SO2: 1,
            NO2: 18,
            O2: 24,
            NO: 0.5,
            N2O: 1.3,
            HNO3: 2,
        },
        initialConcentrations: {
            H2O: 52,
            H2S: 0,
            SO2: 1,
            NO2: 9,
            O2: 30,
            NO: 13,
        },
        name: "Exp1_C",
        pressure: 100,
        temperature: 2,
        time: 160,
    },
    {
        finalConcentrations: {
            H2O: 47,
            H2S: 0,
            SO2: 0.9,
            NO2: 16.4,
            O2: 62,
            NO: 0.3,
            N2O: 1.4,
            HNO3: 3,
        },
        initialConcentrations: {
            H2O: 52,
            H2S: 0,
            SO2: 1,
            NO2: 9,
            O2: 68,
            NO: 13,
        },
        name: "Exp1_D",
        pressure: 100,
        temperature: 2,
        time: 277,
    },
    {
        finalConcentrations: {
            H2O: 48,
            H2S: 0,
            SO2: 0.8,
            NO2: 16,
            O2: 67,
            NO: 0.3,
            N2O: 1.5,
            HNO3: 3.3,
        },
        initialConcentrations: {
            H2O: 52,
            H2S: 0,
            SO2: 1,
            NO2: 9,
            O2: 73,
            NO: 13,
        },
        name: "Exp1_E",
        pressure: 100,
        temperature: 2,
        time: 335,
    },
    {
        finalConcentrations: {
            H2O: 46,
            H2S: 0,
            SO2: 4.4,
            NO2: 15.3,
            O2: 66,
            NO: 0.3,
            N2O: 1.5,
            HNO3: 3,
        },
        initialConcentrations: {
            H2O: 52,
            H2S: 0,
            SO2: 4.6,
            NO2: 9,
            O2: 73,
            NO: 13,
        },
        name: "Exp1_F",
        pressure: 100,
        temperature: 2,
        time: 395,
    },
    {
        finalConcentrations: {
            H2O: 47,
            H2S: 0,
            SO2: 4.3,
            NO2: 13.2,
            O2: 66,
            NO: 0.3,
            N2O: 1.3,
            HNO3: 2.8,
        },
        initialConcentrations: {
            H2O: 52,
            H2S: 0,
            SO2: 4.6,
            NO2: 0,
            O2: 73,
            NO: 13,
        },
        name: "Exp1_G",
        pressure: 100,
        temperature: 2,
        time: 477,
    },
    {
        finalConcentrations: {
            H2O: 50,
            H2S: 0,
            SO2: 1,
            NO2: 10,
            O2: 93,
            NO: 7.5,
            N2O: 1,
            HNO3: 0,
        },
        initialConcentrations: {
            H2O: 46,
            H2S: 0,
            SO2: 0.8,
            NO2: 10.6,
            O2: 0,
            NO: 11.9,
        },
        name: "Exp2_A",
        pressure: 100,
        temperature: 2,
        time: 32,
    },
    {
        finalConcentrations: {
            H2O: 44,
            H2S: 0,
            SO2: 0,
            NO2: 18.5,
            O2: 90,
            NO: 0,
            N2O: 1.5,
            HNO3: 5.5,
        },
        initialConcentrations: {
            H2O: 46,
            H2S: 0,
            SO2: 0.8,
            NO2: 10.6,
            O2: 100,
            NO: 11.9,
        },
        name: "Exp2_B",
        pressure: 100,
        temperature: 2,
        time: 63,
    },
    {
        finalConcentrations: {
            H2O: 45,
            H2S: 0,
            SO2: 0,
            NO2: 19,
            O2: 90,
            NO: 0,
            N2O: 1.5,
            HNO3: 5,
        },
        initialConcentrations: {
            H2O: 46,
            H2S: 0,
            SO2: 1,
            NO2: 10.6,
            O2: 100,
            NO: 11.9,
        },
        name: "Exp2_F",
        pressure: 100,
        temperature: 2,
        time: 472,
    },
    {
        finalConcentrations: {
            H2O: 43,
            H2S: 0,
            SO2: 0.5,
            NO2: 19,
            O2: 90,
            NO: 0,
            N2O: 1.5,
            HNO3: 5,
        },
        initialConcentrations: {
            H2O: 46,
            H2S: 1.4,
            SO2: 1,
            NO2: 10.6,
            O2: 100,
            NO: 11.9,
        },
        name: "Exp2_G",
        pressure: 100,
        temperature: 2,
        time: 571,
    },
    {
        finalConcentrations: {
            H2O: 45,
            H2S: 0,
            SO2: 1,
            NO2: 7,
            O2: 0,
            NO: 10.5,
            N2O: 1,
            HNO3: 0,
        },
        initialConcentrations: {
            H2O: 47,
            H2S: 0.6,
            SO2: 1,
            NO2: 10.6,
            O2: 0,
            NO: 11.9,
        },
        name: "Exp2_H",
        pressure: 100,
        temperature: 2,
        time: 762,
    },
];
