FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu

RUN apt-get update

RUN apt-get install -y python3.11-dev

RUN apt-get install -y python3.11-venv

RUN apt-get install -y curl

RUN apt-get remove -y nodejs npm || true

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

RUN node -v && npm -v

