"""refactor simulation to use model_inputs table

Revision ID: 01aaa143d690
Revises: c35588effcc4
Create Date: 2026-01-21 16:50:46.128272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01aaa143d690"
down_revision: Union[str, Sequence[str], None] = "c35588effcc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_inputs",
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("results", sa.Column("model_input_id", sa.Uuid(), nullable=False))
    op.drop_constraint(
        op.f("results_simulation_id_fkey"), "results", type_="foreignkey"
    )
    op.create_foreign_key(None, "results", "model_inputs", ["model_input_id"], ["id"])
    op.drop_column("results", "simulation_id")
    op.drop_column("simulations", "model_id")
    op.drop_column("simulations", "parameters")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulations",
        sa.Column(
            "parameters",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "simulations",
        sa.Column("model_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "results",
        sa.Column("simulation_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "results", type_="foreignkey")  # type: ignore # Alembic accepts contraint name as string or None
    op.create_foreign_key(
        op.f("results_simulation_id_fkey"),
        "results",
        "simulations",
        ["simulation_id"],
        ["id"],
    )
    op.drop_column("results", "model_input_id")
    op.drop_table("model_inputs")
    # ### end Alembic commands ###
