"""Added model_version to simulation

Revision ID: 60afa15c63a4
Revises: c35588effcc4
Create Date: 2025-11-18 10:43:26.687119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60afa15c63a4"
down_revision: Union[str, Sequence[str], None] = "c35588effcc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("results", sa.Column("model_version", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("results", "model_version")
    # ### end Alembic commands ###
