"""Add adapter version

Revision ID: 95cea2f880b2
Revises: 01aaa143d690
Create Date: 2026-02-12 14:57:32.026783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95cea2f880b2"
down_revision: Union[str, Sequence[str], None] = "01aaa143d690"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("results", sa.Column("model_version", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("results", "model_version")
    # ### end Alembic commands ###
