name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4


    - name: InstallDependencies(withdebugging)
      run: |
        pwd
        ls -la # List files to verify that package-lock.json is there         
        cat package-lock.json  # Check the contents of the lock file         
        npm ci --verbose  # Run the command

    - name: Build Vitest (if present)
      run: npm run build --if-present

    - name: Run Tests
      run: npm run test

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'