name: Run prettier
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Check formatting with Prettier
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
          FILES=$(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }}/frontend origin/${{ github.head_ref }}/frontend || true)
          if [ -n "$FILES" ]; then
            echo "Files to check:"
            echo "$FILES"
            npx prettier --check $FILES
          else
            echo "No files to check. Skipping Prettier check."
          fi
        working-directory: ./frontend
