name: Run prettier
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache:
            key: ${{ runner.os }}-node-${{ matrix.node-version }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Check cache hit
        run: |
          if [ -d "${{ github.workspace }}/.npm" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Check formatting with Prettier
        run: npm run prettier:check
        working-directory: ./frontend
